package codegen

// This code generated by go generate.
// DO NOT EDIT BY HAND!

type User struct {
	Bio             string                 `json:"bio"`
	Education       map[string]interface{} `json:"education"`
	Full_name       string                 `json:"full_name"`
	Hobbies         []interface{}          `json:"hobbies"`
	Id              string                 `json:"id"`
	Is_business     bool                   `json:"is_business"`
	Profile_picture string                 `json:"profile_picture"`
	Salary          float64                `json:"salary"`
	Username        string                 `json:"username"`
	Website         string                 `json:"website"`
}
